- bundles/alpha.model.xtext/src/alpha/model/AlphaModelLoader.java
Adds the main AlphaModelLoader class definition. I don't know why this wasn't in the main branch prior to forking, but it is needed in order to read *.alpha files.
> add AlphaModelLoader class to alpha.model.xtext

- releng/alpha.language.target/alpha.language.target.target
- scripts/resources/required-plugins.p2f
A while back the gecos inria update sites had certificate issues. This caused our AlphaZ and alpha-language builds to break. I set up temporary mirror sites for gecos at CSU, and pointed our build scripts to those mirror sites. The certificate issues were fixed and the AlphaZ script pointers were updated (https://github.com/CSU-CS-Melange/AlphaZ/pull/8)  but I never updated the alpha-language scripts.
This PR updates the alpha-language build scripts to point back to the true inria gecos update sites.
> Use inria update sites for gecos

- .github/workflows/build.yml
- scripts/make-update-site-readme.sh
Now we no longer build the eclipse bundles. This is hard to maintain longterm and more often than not, it has been easier to use the `scripts/make-bundle.sh` script to build the bundle locally when needed.
> CI updates

- .github/workflows/build.yml
This adds code coverage collection and reporting to code climate. This complements the changes to the build image in commit c6ff90c85671148d7bf6cb902356139b58c9c23e of the alpha-language-image repo.
The code climate `cc-test-reporter` is now available in the build image. This is called before and after to set up instrumentation required to collect code coverage information. Following junit testing, the results are uploaded to code climate using the id supplied in the `CC_TEST_REPORTER_ID` env var. This is the id assigned to the alpha-language repo in code climate.
> Add code coverage instrumentation

- bundles/alpha.model/model/alpha.xcore
- bundles/alpha.model/src/alpha/model/transformation/automation/SimplifyingReductionOptimalSimplificationAlgorithm.xtend
This changes the optimal simplification implementation so that it explores and returns all possible simplifications.
For example, given this input:
```
affine example [N] -> {  : N >= 11 }
inputs
X : {[i]: 0 <= i <= 2N }
outputs
Y : {[i]: 0 <= i <= N }
when {  : N >= 11 } let
Y = reduce(+, (i,j->i), {[i, j]: 0 <= j <= 2i } : (i,j->j)@X);
.
```
Now both possible simplifications are returned:
```
affine example [N] -> {  : N >= 11 }
inputs
X : {[i]: 0 <= i <= 2N }
outputs
Y : {[i]: 0 <= i <= N }
locals
Y_add : {[i0]: 0 <= i0 <= N }
when {  : N >= 11 } let
Y = case  {
{[i0]: i0 = 0 } : Y_add;
(Y_add + (i->i-1)@Y);
};
Y_add = reduce(+, (i,j->i), {[i, j]: i <= N and j >= -1 + 2i and 0 <= j <= 2i } : (i,j->j)@X);
.
affine example [N] -> {  : N >= 11 }
inputs
X : {[i]: 0 <= i <= 2N }
outputs
Y : …
```
> Simplification dev

- bundles/alpha.model/model/alpha.xcore
- bundles/alpha.model/src-gen/alpha/model/JNIFunction.java
- bundles/alpha.model/src-gen/alpha/model/impl/JNIFunctionImpl.java
- bundles/alpha.model/src-gen/alpha/model/impl/ModelPackageImpl.java
- bundles/alpha.model/src/alpha/model/util/AlphaUtil.xtend
- bundles/alpha.model/xtend-gen/alpha/model/util/AlphaUtil.java
PR #12 ensures that all context and expression domains objs (ISLSet) have named indices.
This does the same thing but for functions (ISLMultiAff).
> Also ensuring any ISLMultiAff domain and ranges are named

- bundles/alpha.model/src/alpha/model/util/FaceLattice.xtend
- bundles/alpha.model/src/alpha/model/util/Facet.xtend
- bundles/alpha.model/src/alpha/model/util/ISLUtil.xtend
- bundles/alpha.model/xtend-gen/alpha/model/util/Facet.java
- bundles/alpha.model/xtend-gen/alpha/model/util/ISLUtil.java
- tests/alpha.model.tests/src/alpha/model/tests/util/FaceLatticeTest.xtend
- tests/alpha.model.tests/xtend-gen/alpha/model/tests/util/FaceLatticeTest.java
Computes the dimensionality of an arbitrary input set as the number of indices less the number of linearly independent effectively saturated constraints.
We don’t need to look at combinations of constraints or anything like that. All we need to do is test whether or not each constraint is effectively saturated based on the definitions in Theorem 1 of GR06.
This correctly handles issue #20, and is needed for issue #22.
---
There are two commits. The first adds several other isl helper functions. The second does the dimensionality computation.
> Compute the dimensionality using Theorem 1 from GR06

- .github/workflows/build.yml
- bundles/alpha.model/src/alpha/model/transformation/reduction/NormalizeReductionDeep.xtend
- bundles/alpha.model/xtend-gen/alpha/model/transformation/reduction/NormalizeReductionDeep.java
- tests/alpha.model.tests/resources/src-valid/transformation-reduction-tests/normalize-reduction-deep/normalizeReductionDeep.alpha
- tests/alpha.model.tests/src/alpha/model/tests/transformation/reduction/NormalizeReductionDeepTest.xtend
- tests/alpha.model.tests/xtend-gen/alpha/model/tests/transformation/reduction/NormalizeReductionDeepTest.java
It calls NormalizeReduction on all reductions within an AST as long as the reduction isn't already the top-level expression within an equation.
> Adding a NormalizeReductionDeep visitor

- bundles/alpha.model/src/alpha/model/transformation/Normalize.xtend
- bundles/alpha.model/src/alpha/model/transformation/RaiseDependence.xtend
- bundles/alpha.model/src/alpha/model/util/ISLUtil.xtend
- bundles/alpha.model/xtend-gen/alpha/model/transformation/Normalize.java
- bundles/alpha.model/xtend-gen/alpha/model/transformation/RaiseDependence.java
- bundles/alpha.model/xtend-gen/alpha/model/util/ISLUtil.java
- tests/alpha.model.tests/resources/src-valid/transformation-tests/raise-dependence/raiseDependence.alpha
- tests/alpha.model.tests/src/alpha/model/tests/transformations/RaiseDependenceTest.xtend
- tests/alpha.model.tests/xtend-gen/alpha/model/tests/transformations/RaiseDependenceTest.java
The previous iteration of the rule appeared to be the inverse of the associated normalization rule, but was not. Instead, information about the restriction domain was being lost in some cases, resulting in incorrect programs. This was most easily seen when applying dependence raising to a prefix scan equation. A test for this was added to ensure this scenario doesn't occur again.
> Fixing the dependence raising rule for restrictions

- bundles/alpha.model/src/alpha/model/transformation/RaiseDependence.xtend
- bundles/alpha.model/xtend-gen/alpha/model/transformation/RaiseDependence.java
After RaiseDependence is called, reduce expressions will be of the form: `reduce(op, f, g@E)`. The expression E can be arbitrarily complex and there are times when we would like to separate it into a new local variable. This will be needed for the implementation of the optimal simplifying reductions algorithm.
In our original proof-of-concepts, we had a separate class called RaiseDependenceAndIsolate which extended RaiseDependence and did the hoisting. A separate class is probably overkill since it only requires a single new dispatch method for reduction nodes. This PR simply overloads the `apply` method in RaiseDependence with a new flag called `hoistFromReduce` to indicate when this separation should be done.
Now when `RaiseDependence.apply(visitable, true)` is called, reduce …
> Allow for hoisting raised dependence expression out of reductions

- bundles/alpha.model/src/alpha/model/transformation/RaiseDependence.xtend
- bundles/alpha.model/src/alpha/model/util/DefaultAlphaVisitor.java
- bundles/alpha.model/xtend-gen/alpha/model/transformation/RaiseDependence.java
Dependence raising now will aim for a "reduce(restrict(dependence(expr)))" pattern, which is more usable for simplifying reductions as it exposes more reuse.
Also fixes the concurrent modification issue in the default alpha visitor.
Fixes #39, fixes #40.
> Raise Dependence Leaves Restrict as Top of Reductions

- .github/workflows/build.yml
- bundles/alpha.model/src/alpha/model/transformation/StandardizeNames.xtend
- bundles/alpha.model/src/alpha/model/util/AlphaUtil.xtend
- bundles/alpha.model/xtend-gen/alpha/model/transformation/StandardizeNames.java
- bundles/alpha.model/xtend-gen/alpha/model/util/AlphaUtil.java
- tests/alpha.model.tests/resources/src-valid/transformation-tests/standardize-names/standardizeNames.alpha
- tests/alpha.model.tests/src/alpha/model/tests/transformations/StandardizeNamesTest.xtend
- tests/alpha.model.tests/xtend-gen/alpha/model/tests/transformations/StandardizeNamesTest.java
Add a transformation to standardize names throughout an Alpha system. This is done top-down, that way a parent's names are set before visiting its children.
This PR also adds a function which performs a deep copy on an AST (or part of an AST), as both Louis and I will need it soon.
When updating the names within an expression, the names to use are determined as follows:
1. If the expression's parent is a standard equation:
1. Names on the left-hand side of the equation.
2. The names used when declaring the variable.
3. Default names are selected.
2. If the parent is a dependence expression:
1. The names from the parent dependence function's output dimensions are used.
3. If the parent is a reduce expression:
1. The names from the parent reduction's projection function's output dimensions …
> Standardize Names Transformation and Copy AST

- .github/workflows/build.yml
- bundles/alpha.model/src/alpha/model/ComplexityCalculator.xtend
- bundles/alpha.model/src/alpha/model/transformation/automation/OptimalSimplifyingReductions.xtend
- bundles/alpha.model/xtend-gen/alpha/model/ComplexityCalculator.java
- tests/alpha.model.tests/META-INF/MANIFEST.MF
- tests/alpha.model.tests/src/alpha/model/tests/ComplexityCalculatorTest.xtend
- tests/alpha.model.tests/src/alpha/model/tests/util/AlphaTestUtil.java
- tests/alpha.model.tests/xtend-gen/alpha/model/tests/ComplexityCalculatorTest.java
Fixes issue #46 
Now the complexity calculation step used by simplifying reductions lives in it own class. This will be better if/when it needs to be augmented down the road.
> Move complexity calculation to a separate class

- .github/workflows/build.yml
- bundles/alpha.model/src/alpha/model/matrix/MatrixOperations.java
- bundles/alpha.model/src/alpha/model/transformation/automation/OptimalSimplifyingReductions.xtend
- bundles/alpha.model/src/alpha/model/transformation/reduction/SplitReduction.xtend
- bundles/alpha.model/src/alpha/model/util/AlphaOperatorUtil.xtend
- bundles/alpha.model/src/alpha/model/util/AlphaUtil.xtend
- bundles/alpha.model/src/alpha/model/util/ISLUtil.xtend
- bundles/alpha.model/xtend-gen/alpha/model/transformation/reduction/SplitReduction.java
- bundles/alpha.model/xtend-gen/alpha/model/util/AlphaOperatorUtil.java
- bundles/alpha.model/xtend-gen/alpha/model/util/AlphaUtil.java
- bundles/alpha.model/xtend-gen/alpha/model/util/ISLUtil.java
- tests/alpha.model.tests/resources/src-valid/transformation-reduction-tests/split-reduction/splitReduction.alpha
- tests/alpha.model.tests/src/alpha/model/tests/transformation/reduction/SplitReductionTest.xtend
- tests/alpha.model.tests/xtend-gen/alpha/model/tests/transformation/reduction/SplitReductionTest.java
This implements the splitting steps for simplification that may be required when the reduction operator does not admit an inverse. This involves small changes the OptimalSimplifyingReductions, a new dynamic programming step for splitting is introduced.
The bulk of the new logic is in alpha.model.transformation.reduction.SplitReduction. Essentially, given a reduce expression with 1D accumulation and/or 1D reuse space, we construct the list of useful candidate splits for simplification. The definition of a useful split is one that both:
* separates the reduction body into two non-empty pieces
* exposes a new boundary or invariant face
Then a new candidate DPStep is inserted into the OptimalSimplifyingReductions flow for each.
See the comments in …
> Maximal simplification

- bundles/alpha.model/src/alpha/model/transformation/Normalize.xtend
- bundles/alpha.model/xtend-gen/alpha/model/transformation/Normalize.java
- tests/alpha.model.tests/resources/src-valid/transformation-tests/normalize/multipleCaseExprs.alpha
Fixes issues #55 and #44.
Previously, normalize did not handle binary expressions with multiple case expressions correctly. Now it does, and correctly transforms this:
```
affine test11 [N] -> {  : N >= 6 }
inputs
X : {[i]: -3 + N <= i < 2N }
outputs
Y : {[i]: 0 <= i <= N }
when {  : N >= 6 } let
Y[i] = (case  {
{: i = 0 } : 0[];
{: 0 < i < N } : 12[];
{: i = N } : 1[];
} + case  {
{: i <= -4 + N } : 5[];
X[i];
});
.
```
into this:
```
affine test11 [N] -> {  : N >= 6 }
inputs
X : {[i]: -3 + N <= i < 2N }
outputs
Y : {[i]: 0 <= i <= N }
when {  : N >= 6 } let
Y[i] = case  {
{: i = 0 } : (0[] + 5[]);
{: 0 < i <= -4 + N } : (12[] + 5[]);
{: -3 + N <= i < N } : (12[] + X);
{: i = N } : (1[] + X);
};
.
```
> Fix normalization of binary expressions with multiple case expressions

- bundles/alpha.codegen/model/simpleC.xcore
- bundles/alpha.codegen/src-gen/alpha/codegen/BaseDataType.java
- bundles/alpha.codegen/src-gen/alpha/codegen/impl/CodegenPackageImpl.java
- bundles/alpha.codegen/src/alpha/codegen/Factory.xtend
- bundles/alpha.codegen/src/alpha/codegen/ProgramPrinter.xtend
- bundles/alpha.codegen/src/alpha/codegen/writeC/Common.xtend
- bundles/alpha.codegen/src/alpha/codegen/writeC/DependenceExprConverter.xtend
- bundles/alpha.codegen/src/alpha/codegen/writeC/ExprConverter.xtend
- bundles/alpha.codegen/src/alpha/codegen/writeC/ReduceExprConverter.xtend
- bundles/alpha.codegen/src/alpha/codegen/writeC/SystemConverter.xtend
- bundles/alpha.codegen/xtend-gen/alpha/codegen/Factory.java
- bundles/alpha.codegen/xtend-gen/alpha/codegen/ProgramPrinter.java
- bundles/alpha.codegen/xtend-gen/alpha/codegen/writeC/Common.java
- bundles/alpha.codegen/xtend-gen/alpha/codegen/writeC/DependenceExprConverter.java
- bundles/alpha.codegen/xtend-gen/alpha/codegen/writeC/ExprConverter.java
- bundles/alpha.codegen/xtend-gen/alpha/codegen/writeC/ReduceExprConverter.java
- bundles/alpha.codegen/xtend-gen/alpha/codegen/writeC/SystemConverter.java
- bundles/alpha.model/src/alpha/model/util/ShowLegacyAlpha.xtend
- bundles/alpha.model/xtend-gen/alpha/model/util/ShowLegacyAlpha.java
- tests/alpha.codegen.tests/src/alpha/codegen/tests/writeC/SystemConverterManualTest.xtend
- tests/alpha.codegen.tests/xtend-gen/alpha/codegen/tests/writeC/SystemConverterManualTest.java
Allows the code generator to treat values in AlphaZ as any data type. Intended to allow using an "int" or "long" for consistent verification of correctness.
Fixes #63
> Codegen int or float

- bundles/alpha.codegen/src/alpha/codegen/writeC/Common.xtend
- bundles/alpha.codegen/xtend-gen/alpha/codegen/writeC/Common.java
Incorrect results were being returned because of commas at the end of "case" expressions within a "switch" expression block. Xtend uses commas to indicate fall through, which was causing the wrong result to be returned.
See: https://eclipse.dev/Xtext/xtend/documentation/203_xtend_expressions.html#fall-through
Fixes #69
> Removing commas from a switch expression which caused incorrect results

- bundles/alpha.model/src-gen/alpha/model/matrix/impl/MatrixPackageImpl.java
- bundles/alpha.model/src/alpha/model/transformation/automation/OptimalSimplifyingReductions.xtend
This modifies OptimalSimplifyingReductions. Now:
* splitting is turned off by default
* the target complexity can be specified
This is primarily to make invoking simplification from [acc](https://github.com/CSU-CS-Melange/alpha-codegen) easier. This is intended to be used with the changes in [alpha-codegen/pull/2](https://github.com/CSU-CS-Melange/alpha-codegen/pull/2).
> Add hooks to optimal simplifying reductions

- bundles/alpha.model/src/alpha/model/transformation/automation/OptimalSimplifyingReductions.xtend
- bundles/alpha.model/src/alpha/model/transformation/reduction/SimplifyingReductions.xtend
- bundles/alpha.model/xtend-gen/alpha/model/transformation/automation/OptimalSimplifyingReductions.java
- bundles/alpha.model/xtend-gen/alpha/model/transformation/reduction/SimplifyingReductions.java
Removes the RaiseDependence step from OptimalSimplifyingReductions. It is not needed since the ShareSpaceAnalysis provides the same information needed to construct the reuse space. This also removes many of the duplicates reported by OSR.
Changes the SimplifyingReduction.generateCandidateReuseVectors so that it allows cases when the reuse and accumulation space have a non-trivial intersection. This should be allowed per GR06 > Algorithm 2 > Step 6. Before this fix, DP step 6a was not performed (when it should be) if 6b was performed.
> Fixes to simplification

- bundles/alpha.model/src/alpha/model/util/AffineFactorizer.xtend
- bundles/alpha.model/xtend-gen/alpha/model/util/AffineFactorizer.java
- tests/alpha.model.tests/src/alpha/model/tests/util/AffineFactorizerTest.xtend
- tests/alpha.model.tests/xtend-gen/alpha/model/tests/util/AffineFactorizerTest.java
Only factorize the linear terms so that if you factorize the following:
```
(i,j -> i+3)
(i,j -> i+N)
```
You end up with the following as the common factor:
```
(i,j -> i)
```
Instead of the following, which has more dimensions than necessary:
```
(i,j -> N-3, i+3)
```
> Raise Dependence: Only Factorize the Linear Terms

- .github/workflows/build.yml
- .github/workflows/deploy.yml
Changing the use of the "cache" action in the "deploy" job, as it did not work correctly. It's being replaced with uploading an artifact in "build", then downloading that in "deploy". See the link below for details on how these work.
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/storing-workflow-data-as-artifacts#passing-data-between-jobs-in-a-workflow
Per the link below, artifacts are intended for passing files from one job to another within the same workflow instance, while caches are intended to pass files between workflow instances.
https://echobind.com/post/difference-between-artifacts-and-cache-in-GitHub-Actions
> GitHub hosted actions v2

- .github/workflows/deploy.yml
Turns out, uploaded artifacts will not retain their permissions. This caused an issue in the deploy step, which ran a script that was saved this way. To fix this, I added a step that makes the script executable.
> Fixing file permissions in the deploy job

- bundles/alpha.codegen/src/alpha/codegen/demandDriven/WriteC.xtend
- bundles/alpha.codegen/xtend-gen/alpha/codegen/demandDriven/WriteC.java
> ACC fix for duplicate macro indices
